# Generated by Django 4.1.5 on 2023-01-08 03:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Note",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=128, verbose_name="タイトル")),
                ("content", models.TextField(blank=True, verbose_name="記事")),
                (
                    "is_publish_mail",
                    models.BooleanField(default=False, verbose_name="メール発行"),
                ),
                (
                    "attach_file",
                    models.FileField(
                        upload_to="uploads/%Y/%m/%d/", verbose_name="添付ファイル"
                    ),
                ),
                (
                    "attach_image",
                    models.ImageField(
                        upload_to="images/%Y/%m/%d/", verbose_name="添付画像"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="投稿日"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新日")),
                (
                    "created_by",
                    models.ForeignKey(
                        default="名無しさん",
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="投稿者",
                    ),
                ),
            ],
            options={"db_table": "notes",},
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tag_name", models.CharField(max_length=30, verbose_name="タグ")),
                (
                    "note_to",
                    models.ManyToManyField(
                        related_query_name="tag",
                        to="forum_note.note",
                        verbose_name="投稿",
                    ),
                ),
            ],
            options={"db_table": "tags",},
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(blank=True, verbose_name="コメント")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="投稿日"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新日")),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="投稿者",
                    ),
                ),
                (
                    "note_to",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="forum_note.note",
                        verbose_name="投稿",
                    ),
                ),
            ],
            options={"db_table": "comments",},
        ),
    ]
