# Generated by Django 4.1.5 on 2023-01-08 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forum_note", "0002_note_open_range_python"),
    ]

    operations = [
        migrations.RemoveField(model_name="note", name="open_range_python",),
        migrations.AddField(
            model_name="note",
            name="open_range",
            field=models.CharField(
                default="subscribe", max_length=20, verbose_name="公開範囲"
            ),
        ),
    ]
