# Generated by Django 4.1.5 on 2023-01-08 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forum_note", "0003_remove_note_open_range_python_note_open_range"),
    ]

    operations = [
        migrations.AlterField(
            model_name="note",
            name="open_range",
            field=models.CharField(
                default="subscribers", max_length=20, verbose_name="公開範囲"
            ),
        ),
    ]
