# Generated by Django 4.1.5 on 2023-01-08 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forum_note", "0004_alter_note_open_range"),
    ]

    operations = [
        migrations.AlterField(
            model_name="note",
            name="attach_file",
            field=models.FileField(
                blank=True, upload_to="uploads/%Y/%m/%d/", verbose_name="添付ファイル"
            ),
        ),
        migrations.AlterField(
            model_name="note",
            name="attach_image",
            field=models.ImageField(
                blank=True, upload_to="images/%Y/%m/%d/", verbose_name="添付画像"
            ),
        ),
    ]
