# Generated by Django 4.1.5 on 2023-01-08 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("forum_note", "0005_alter_note_attach_file_alter_note_attach_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="note_to",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="forum_note.note",
                verbose_name="投稿",
            ),
        ),
    ]
