# Generated by Django 4.1.5 on 2023-01-08 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forum_note", "0006_alter_comment_note_to"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="note_to",
            field=models.ManyToManyField(
                related_query_name="tags", to="forum_note.note", verbose_name="投稿"
            ),
        ),
    ]
