# Generated by Django 4.1.5 on 2023-01-14 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forum_note", "0008_tag_search_word"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="attach_file",
            field=models.FileField(
                blank=True, upload_to="uploads/%Y/%m/%d/", verbose_name="添付ファイル"
            ),
        ),
        migrations.AddField(
            model_name="comment",
            name="attach_image",
            field=models.ImageField(
                blank=True, upload_to="images/%Y/%m/%d/", verbose_name="添付画像"
            ),
        ),
    ]
