# Generated by Django 4.1.5 on 2023-01-08 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="username",
            field=models.CharField(
                default="名無しさん", max_length=150, verbose_name="ユーザー名"
            ),
        ),
    ]
